env:
  global:
    - CC_TEST_REPORTER_ID=f4247e1b007aa38ed314c32b6e25be8617336be2a34b0fe906b57119d26434c3
language: ruby
rvm:
  # Build on the latest stable of all supported Rubies (https://www.ruby-lang.org/en/downloads/):
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
cache: bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rubocop
  - bundle exec rspec spec --format documentation
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
